# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        Dialog.setStyleSheet("")
        self.lineEdit_id = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_first = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_first.setGeometry(QtCore.QRect(10, 90, 211, 31))
        self.lineEdit_first.setText("")
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.lineEdit_last = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_last.setGeometry(QtCore.QRect(10, 130, 211, 31))
        self.lineEdit_last.setObjectName("lineEdit_last")
        self.pushButton_add = QtWidgets.QPushButton(Dialog)
        self.pushButton_add.setGeometry(QtCore.QRect(280, 60, 101, 31))
        self.pushButton_add.setStyleSheet("background-color: rgb(61, 62, 255);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(10, 170, 211, 31))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton_modify = QtWidgets.QPushButton(Dialog)
        self.pushButton_modify.setGeometry(QtCore.QRect(280, 110, 101, 31))
        self.pushButton_modify.setStyleSheet("background-color: rgb(61, 62, 255);")
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.pushButton_delet = QtWidgets.QPushButton(Dialog)
        self.pushButton_delet.setGeometry(QtCore.QRect(280, 160, 101, 31))
        self.pushButton_delet.setStyleSheet("background-color: rgb(61, 62, 255);\n"
"")
        self.pushButton_delet.setObjectName("pushButton_delet")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 10, 181, 31))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(15, 231, 371, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton_exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_exit.setGeometry(QtCore.QRect(280, 210, 101, 20))
        self.pushButton_exit.setStyleSheet("background-color: rgb(61, 62, 255);")
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Form"))
        self.lineEdit_id.setPlaceholderText(_translate("Dialog", "  Enter student ID"))
        self.lineEdit_first.setPlaceholderText(_translate("Dialog", "  Enter student First Name"))
        self.lineEdit_last.setPlaceholderText(_translate("Dialog", "  Enter student Last Name"))
        self.pushButton_add.setText(_translate("Dialog", "ADD"))
        self.lineEdit_email.setPlaceholderText(_translate("Dialog", "  Enter student Email"))
        self.pushButton_modify.setText(_translate("Dialog", "MODIFY"))
        self.pushButton_delet.setText(_translate("Dialog", "DELETE"))
        self.label.setText(_translate("Dialog", "  STUDENTS  INFORMATION"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "FIRST NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "LAST NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "EMAIL"))
        self.pushButton_exit.setText(_translate("Dialog", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
