# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(40, 430, 321, 41))
        self.b1.setStyleSheet("\n"
"background-color: rgb(1, 47, 82);")
        self.b1.setObjectName("b1")
        self.b3 = QtWidgets.QPushButton(Form)
        self.b3.setGeometry(QtCore.QRect(210, 320, 171, 31))
        self.b3.setStyleSheet("\n"
"background-color: rgb(1, 47, 82);")
        self.b3.setObjectName("b3")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(20, 320, 171, 31))
        self.b2.setStyleSheet("\n"
"background-color: rgb(1, 47, 82);")
        self.b2.setObjectName("b2")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(20, 250, 361, 41))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(20, 190, 361, 41))
        self.username.setText("")
        self.username.setObjectName("username")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b1.setText(_translate("Form", "R E G I S T E R"))
        self.b3.setText(_translate("Form", "Admin Login"))
        self.b2.setText(_translate("Form", "Student Login"))
        self.password.setPlaceholderText(_translate("Form", "  Enter the password"))
        self.username.setPlaceholderText(_translate("Form", "  Enter the username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
