# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        self.stdreg = QtWidgets.QPushButton(Form)
        self.stdreg.setGeometry(QtCore.QRect(20, 310, 171, 31))
        self.stdreg.setStyleSheet("\n"
"background-color: rgb(1, 47, 82);")
        self.stdreg.setObjectName("stdreg")
        self.adreg = QtWidgets.QPushButton(Form)
        self.adreg.setGeometry(QtCore.QRect(210, 310, 171, 31))
        self.adreg.setStyleSheet("\n"
"background-color: rgb(1, 47, 82);")
        self.adreg.setObjectName("adreg")
        self.username = QtWidgets.QLineEdit(Form)
        self.username.setGeometry(QtCore.QRect(20, 120, 361, 41))
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(20, 180, 361, 41))
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.confirmpassword = QtWidgets.QLineEdit(Form)
        self.confirmpassword.setGeometry(QtCore.QRect(20, 240, 361, 41))
        self.confirmpassword.setText("")
        self.confirmpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassword.setObjectName("confirmpassword")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stdreg.setText(_translate("Form", "Registrate as student"))
        self.adreg.setText(_translate("Form", "Registrate as admin"))
        self.username.setPlaceholderText(_translate("Form", "  Enter the username"))
        self.password.setPlaceholderText(_translate("Form", "  Enter the password"))
        self.confirmpassword.setPlaceholderText(_translate("Form", "  Confirm the password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
